- hosts: managers
  become: true
  roles:
  - docker
  - manager

- hosts: managers
  become: true
  roles:
  - managerclonerepo
  - stackdeploy


- hosts: workers
  become: true
  roles:
  - docker
  - worker