---
# tasks file for docker
- name: Install python3 pip
  apt:
    pkg:
    - python3
    - python3-pip
    state: latest
    update_cache: true

- name: update and upgrade apt
  apt:
    upgrade: true
    update_cache: true

- name: 'Install docker requirements'
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    state: latest
    update_cache: true

- name: 'Add GPG Key'
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: 'Add apt-repo'
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable

- name: 'Install docker ce'
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
  

- name: 'Install docker'
  pip:
    name: docker
  register: docker_info

- name: 'Install Jsondiff'
  pip:
    name: jsondiff